server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            enabled: true
            charset: UTF-8
            force: true
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/k15?useUnicode=true&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
        hikari:
            idle-timeout: 60000
            maximum-pool-size: 30
            minimum-idle: 10
    thymeleaf:
        prefix: classpath:/templates/                          # 前缀
        suffix: .html                                          # 后缀
        cache: false                                           # 是否缓存，开发阶段使用false，热部署
    servlet:
        multipart:
            max-request-size: 30MB                             # 单个请求的文件总大小上限
            max-file-size: 30MB                                # 单个文件的最大上限
    redis:
        host: 192.168.160.128
        port: 6379
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0

mybatis-plus:
    type-aliases-package: com.woniu.entity                      #别名包配置
#    mapper-locations: classpath:com/woniu/mapper/*.xml          #当mapper接口和mapper.xml在同一个目录下时，可以省略
    configuration:
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl     #日志配置
        map-underscore-to-camel-case: false                     #驼峰配置

pagehelper:
    reasonable: true
    helper-dialect: mysql   # 指定数据库类型，如果不指定，框架会自动判断，如果框架判断有问题，自己在手动指定

